Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,7 +25,7 @@ jobs:
       run: |
         VERSION_NUMBER_OLD=`grep -Po "${{ env.VERSION_REGEX }}" ./${{ env.VERSION_FILE }}`
         echo "VERSION_OLD=$VERSION_NUMBER_OLD" >> "$GITHUB_ENV"
-        echo "Old version number: {{ env.VERSION_OLD }}"
+        echo "Old version number: $VERSION_OLD"
 
     - name: Checkout current branch
       uses: actions/checkout@v4
@@ -35,7 +35,7 @@ jobs:
       run: |
         VERSION_NUMBER_NEW=`grep -Po "${{ env.VERSION_REGEX }}" ./${{ env.VERSION_FILE }}`
         echo "VERSION_NEW=$VERSION_NUMBER_NEW" >> "$GITHUB_ENV"
-        echo "New version number: {{ env.VERSION_NEW }}"
+        echo "New version number: $VERSION_NEW"
         
     - name: Download semver script
       shell: bash
@@ -46,7 +46,7 @@ jobs:
     - name: Compare versions
       shell: bash
       run: |
-        ./semver2.sh ${{ env.VERSION_NEW }} ${{ env.VERSION_OLD }} | { read -r var; if [ "$var" -gt 0 ]; then exit 0; else echo "AntiquatedVersionError: downstream version ("${{ env.VERSION_NEW }}") is <= base version ("${{ env.VERSION_OLD }}"). Please update to newer semantic version before merging." && exit 1; fi; }
+        ./semver2.sh $VERSION_NEW $VERSION_OLD | { read -r var; if [ "$var" -gt 0 ]; then exit 0; else echo "AntiquatedVersionError: downstream version ("$VERSION_NEW") is <= base version ("$VERSION_OLD"). Please update to newer semantic version before merging." && exit 1; fi; }
 
   build_game:
     runs-on: ubuntu-latest
@@ -76,7 +76,7 @@ jobs:
       uses: ncipollo/release-action@v1.12.0
       with:
         generateReleaseNotes: true
-        tag: v${{ env.VERSION_NEW }}
+        tag: "v$VERSION_NEW"
         artifacts: ${{ steps.export.outputs.archive_directory }}/*
 
   publish_game:
