Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,57 +1,108 @@
+name: Build Pipeline
+
 on: 
   push:
     branches: [ 'main' ]
 
 env:
+  GODOT_VERSION: 4.2.1
   VERSION_FILE: project.godot
   VERSION_REGEX: config\/version=\"\K[0-9.\-A-z]*
+  VERSION_OLD: 0.0.0
+  VERSION_NEW: 0.0.0
 
-jobs:  
-  export_game:
+jobs:
+  check_version_bump:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout current branch
+      uses: actions/checkout@v4
+      with:
+        ref: ${{ github.base_ref }}
+
+    - name: Extract old version number
+      shell: bash
+      run: |
+        VERSION_NUMBER_OLD=`grep -Po "${{ env.VERSION_REGEX }}" ./${{ env.VERSION_FILE }}`
+        echo "VERSION_OLD=$VERSION_NUMBER_OLD" >> "$GITHUB_ENV"
+        echo "Old version number: {{ env.VERSION_OLD }}"
+
+    - name: Checkout current branch
+      uses: actions/checkout@v4
+
+    - name: Extract new version number
+      shell: bash
+      run: |
+        VERSION_NUMBER_NEW=`grep -Po "${{ env.VERSION_REGEX }}" ./${{ env.VERSION_FILE }}`
+        echo "VERSION_NEW=$VERSION_NUMBER_NEW" >> "$GITHUB_ENV"
+        echo "New version number: {{ env.VERSION_NEW }}"
+        
+    - name: Download semver script
+      shell: bash
+      run: |
+        curl https://raw.githubusercontent.com/Ariel-Rodriguez/sh-semversion-2/main/semver2.sh -o semver2.sh
+        chmod 755 ./semver2.sh
+        
+    - name: Compare versions
+      shell: bash
+      run: |
+        ./semver2.sh ${{ env.VERSION_NEW }} ${{ env.VERSION_OLD }} | { read -r var; if [ "$var" -gt 0 ]; then exit 0; else echo "AntiquatedVersionError: downstream version ("${{ env.VERSION_NEW }}") is <= base version ("${{ env.VERSION_OLD }}"). Please update to newer semantic version before merging." && exit 1; fi; }
+
+  build_game:
     runs-on: ubuntu-latest
     permissions: write-all
-    name: Export Game
+    name: Build Game
+    needs: check_version_bump
     steps:
-    - name: checkout
+    - name: Checkout current branch
       uses: actions/checkout@v4
-    
-    - name: install dependencies
-      shell: bash
-      run: |
-        sudo apt-get update && sudo apt-get install -y rsync
-    
-    - name: extract_version_number
-      shell: bash
-      run: |
-        VERSION_NUMBER=`grep -Po "${{ env.VERSION_REGEX }}" ./${{ env.VERSION_FILE }}`
-        echo "Found Version number: $VERSION_NUMBER"
-    
-    - name: export game
+
+    - name: Export game
       id: export
       uses: firebelley/godot-export@v5.2.1
       with:
-        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_linux.x86_64.zip
-        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_export_templates.tpz
+        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64.zip
+        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}-stable_export_templates.tpz
         relative_project_path: ./
         archive_output: true
-    
-    - name: copy web build
-      shell: bash
-      run: |
-        cp ${{ steps.export.outputs.build_directory }}/Web/ build/web
-        
-      # This release action has worked well for me. However, you can most likely use any release action of your choosing.
-      # https://github.com/ncipollo/release-action
-    - name: create release
+
+    - name: Upload web build
+      uses: actions/upload-artifact@v4
+      with:
+        name: web-zip
+        path: ${{ steps.export.outputs.archive_directory }}/Web.zip
+
+    - name: Create release
       uses: ncipollo/release-action@v1.12.0
       with:
         generateReleaseNotes: true
-        tag: "v$VERSION_NUMBER"
+        tag: v${{ env.VERSION_NEW }}
         artifacts: ${{ steps.export.outputs.archive_directory }}/*
 
-    - name: Deploy 🚀
+  publish_game:
+    runs-on: ubuntu-latest
+    name: Publish to Pages
+    needs: build_game
+    steps:
+    - name: Install dependencies
+      shell: bash
+      run: |
+        sudo apt-get update && sudo apt-get install -y rsync unzip
+    
+    - name: Download web zip
+      uses: actions/download-artifact@v4
+      with:
+        name: web-zip
+    
+    - name: Unzip
+      shell: bash
+      run: |
+        unzip Web.zip
+        ls -al
+
+    - name: Deploy to Github Pages 🚀
       uses: JamesIves/github-pages-deploy-action@v4
       with:
-        folder: build/web
+        folder: Web/
         branch: main
-      
+    
